name: Code Quality Check

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo dnf update -y
        sudo dnf install -y ninja-build g++ clang clang-tools-extra cppcheck clang-format git

    - name: Set up CMake
      uses: lukka/get-cmake@latest

    - name: Configure
      run: cmake -B build -G Ninja -DCMAKE_CXX_COMPILER=g++ -DENABLE_CPPCHECK=ON

    - name: Run CppCheck
      run: |
        CPPCHECK_INCLUDES=$(cat build/cppcheck_includes.txt)

        echo "=== CPPCHECK INCLUDES ==="
        echo "${CPPCHECK_INCLUDES}" | tr ' ' '\n'
        echo "========================"
        
        
        cppcheck \
        --enable=all \
        --suppress=missingIncludeSystem \
        --suppress=missingInclude \
        --std=c++20 \
        ${CPPCHECK_INCLUDES} \

    - name: Check clang-format
      run: |
        find src include -name '*.hpp' -o -name '*.cpp' | xargs clang-format --dry-run --Werror

    - name: Run Lizard
      run: |
        pip install lizard
        lizard src/ include/ -w